spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1998320
    url: jdbc:mysql://127.0.0.1/traceroot?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
  jpa:
    show-sql: true
#  jackson:
#    default-property-inclusion: non_null  #json全局设定非空
#  redis:  #redis的配置
#    host: 127.0.0.1
#    port: 6379


#
server:
  servlet:
    context-path: /traceroot
